### PR TITLE
Promise API proposal

### PR DESCRIPTION
**Pull request by Saionaro**
Hey! Pretty useful lib, thank you!
Here is the raw promise API proposal. What do you think?

Things done:
* Options wrapped in the object;
* Most of the options now are optional - if we have to process jpg-only images, we're allowed now to specify jpg-engine only.
* Added separated module `promise` that exports `compress` method - actual API doesn't change;
* A little bit formatted code examples at the readme for better readability;

Look at example 1

### CODE REVIEW

**Comment by semiromid** [comment]
@Saionaro Hey! 
Thank you! I will take look at your proposal.

**Comment by semiromid** [comment]
> Hey! Pretty useful lib, thank you!
> Here is the raw promise API proposal. What do you think?
> 
> Things done:
> 
> * Options wrapped in the object;
> * Most of the options now are optional - if we have to process jpg-only images, we're allowed now to specify jpg-engine only.
> * Added separated module `promise` that exports `compress` method - actual API doesn't change;
> * A little bit formatted code examples at the readme for better readability;
> 
> Look at example 1

@Saionaro 

I have few questions, please answer me.

> Options wrapped in the object

Why is it needed?

> Added separated module promise that exports compress method - actual API doesn't change;

Why is it needed "Promise"?


> Most of the options now are optional - if we have to process jpg-only images, we're allowed now to specify jpg-engine only.

I try use `promise.js` without engines "gif" and "svg" but i get error - "You didn't turn on [enginesvg], but your input path includes the 'svg' extension ..."

``` NodeJs

    const { compress } = require('compress-images/promise');
    const INPUT_path_to_your_images = 'src/img/**/*.{jpg,JPG,jpeg,JPEG,png,svg,gif}';
    const OUTPUT_path = 'build/img/';

    const processImages = async () => {
        const result = await compress({
            source: INPUT_path_to_your_images,
            destination: OUTPUT_path,
            enginesSetup: {
                jpg: { engine: 'mozjpeg', command: ['-quality', '60']},
                png: { engine: 'pngquant', command: ['--quality=20-50']},
            }
        });

        const { statistics, errors } = result;
        // statistics - all processed images list
        // errors - all errros happened list
        //return result;
    };
```

Need to do it in "promise.js" or edit example in "README.md":
from
` const INPUT_path_to_your_images = 'src/img/**/*.{jpg,JPG,jpeg,JPEG,png,svg,gif}';`
to
`const INPUT_path_to_your_images = 'src/img/**/*.{jpg,JPG,jpeg,JPEG,png}';`


### About your edit README.md

I approve replace `var` to `const`.

I approve of one of the style code examples that you showed. But i think that not all examples need to be rewritten. I think the original style code should remain. Your code style can be added only partially as one of examples.

```
    const compress_images = require('compress-images');
    const INPUT_path_to_your_images = 'src/img/**/*.{jpg,JPG,jpeg,JPEG,png,svg,gif}';
    const OUTPUT_path = 'build/img/';
    
    compress_images(
        INPUT_path_to_your_images,
        OUTPUT_path,
        { compress_force: false, statistic: true, autoupdate: true },
        false,
        { jpg: { engine: 'mozjpeg', command: ['-quality', '60']}},
        { png: { engine: 'pngquant', command: ['--quality=20-50']}},
        { svg: { engine: 'svgo', command: '--multipass'}},
        { gif: { engine: 'gifsicle', command: ['--colors', '64', '--use-col=web']}},
        function(error, completed, statistic) {
            console.log('-------------');
            console.log(error);
            console.log(completed);
            console.log(statistic);
            console.log('-------------');
        }
    );
```

## Conclusion

Still, it would be nice to get approve of your proposal and from other participants.

**Comment by Saionaro** [comment]
@semiromid Thanks for the questions! Here what I guess
> p: Options wrapped in the object
> q: Why is it needed?

It allows us to pass the needed options only. For example in the current API, if we only wanna compress gifs, we're forced to pass all other engines, weird always-`false`, and `compress-images` options which are commonly the same.
It's all about simplify.

> p: Added separated module promise that exports compress method - actual API doesn't change;
> q: Why is it needed "Promise"?

Do you about creating a new module or promised-API at all?

New module - it's since we have breaking changes in API, so we can't just replace current import in `index.js` with the new one.

Promised API - a promise is a kinda standard for async operations in NodeJS nowadays. You can easily and shorten integrate promised functions in your scripts and avoid callback-hell. So, you know.

> q: Need fix it in "promise.js" or edit example in "README.md":

Yes! You're absolutely right, it's my fault. I'll go ahead and fix it.

> q: README staff

You know, I follow only one point here: I try to improve readability. It's hard to understand what happens if you even don't see the whole example on your screen.
In my formatting variant we even can to add comments for each argument as following:

```js
compress_images(
    INPUT_path_to_your_images, // glob path to your images
    OUTPUT_path, // output directory, dont forget trailing slash
    { compress_force: false, statistic: true, autoupdate: true }, // module options, see below for details
    false, // globoption
    { jpg: { engine: 'mozjpeg', command: ['-quality', '60']}}, // jpg-processor setup
    { png: { engine: 'pngquant', command: ['--quality=20-50']}}, // jpg-processor setup
    { svg: { engine: 'svgo', command: '--multipass'}}, // svg-processor setup
    { gif: { engine: 'gifsicle', command: ['--colors', '64', '--use-col=web']}}, // gif-processor setup
    function(error, completed, statistic) { // callback-function
        console.log('-------------');
        console.log(error);
        console.log(completed);
        console.log(statistic);
        console.log('-------------');
    }
);
```

**Comment by semiromid** [comment]
@Saionaro 
Thank you for you answers. 

> Promised API - a promise is a kinda standard for async operations in NodeJS nowadays. You can easily and shorten integrate promised functions in your scripts and avoid callback-hell. So, you know.

But the lib 'compress-images' is async and not requires a lot of callback if it wraper in function. 
```
    function myFun(callback){
        compress_images(INPUT_path_to_your_images, OUTPUT_path, {compress_force: false, statistic: true, autoupdate: true}, false,
                                                    {jpg: {engine: 'mozjpeg', command: ['-quality', '60']}},
                                                    {png: {engine: 'pngquant', command: ['--quality=20-50']}},
                                                    {svg: {engine: 'svgo', command: '--multipass'}},
                                                    {gif: {engine: 'gifsicle', command: ['--colors', '64', '--use-col=web']}}, 
        function(error, completed, statistic){
            return callback(error, completed, statistic);
        });
    }

    myFun(function(error, completed, statistic){
        console.log(statistic);
    });

```
I so understand use Promise it's a matter of convenience for someone.  Ok.  In some cases, it may be convenient.

Please add examples in README.md for the "promise API", how to use it with "onProgress" and "failOnFirstError" parameters.

**Comment by Saionaro** [comment]
@semiromid Hey!
I removed `failOnFirstError` option and added `onProgress` usage example.

I noticed, that we can't guarantee working `failOnFirstError` option well.  An image processing will continue after the first error anyway. So it'll require some deep changes in the core module.

**Comment by semiromid** [comment]
@Saionaro Hey!

If use callback  `onProgress` without the parameter ` completed`, then it is not known when the compression will be completed.

I suggest editing your code:

**promise.js**
[From]
```
if (callback) callback(error, statistic);
```

[To]
```
if (callback) callback(error, statistic, completed);
```

**README.md**

[From]

```
    processImages((error, statistic) => {
        if (error) {
            console.log('Error happen while processing file');
            console.log(error);
            return;
        }

        console.log('Sucefully processed file');

        console.log(statistic)
    });
```

[To]

```
    processImages((error, statistic, completed) => {
        if (error) {
            console.log('Error happen while processing file');
            console.log(error);
            return;
        }

        console.log('Sucefully processed file');

        console.log(statistic)
    });
```
___________________

Promised API

[From]

```
(optional) onProgress (err, statistic): see callback above
```

[To]

```
(optional) onProgress (err, statistic, completed): see callback above
```

**Comment by semiromid** [comment]
@Saionaro Hey!

Are you going to add your improvement?  If yes, then answer me my suggestion I made above.

**Comment by Saionaro** [comment]
@semiromid hi!
I'm pretty busy nowadays. Fill free to add these changes yourself, or give me please a little more time 😅

**Comment by semiromid** [comment]
@Saionaro 

Ok. When I have free time I will do it. Or you.

**Comment by semiromid** [comment]
@Saionaro Thank you very much for your work!

**Comment by Saionaro** [comment]
@semiromid Nice to work with you!

**Pull request merged**
